export type Outcome = 'YES' | 'NO';
export type VenueSide = 'BUY' | 'SELL';
export type TradeIntent = 'ENTER' | 'REDUCE' | 'EXIT' | 'FLIP';
export type InventoryEffect = 'INCREASE' | 'DECREASE' | 'NEUTRAL';

export interface PositionManagerInput {
  /**
   * Identity of the token-specific position ledger being updated.
   */
  marketId: string;
  tokenId: string;
  outcome: Outcome;

  /**
   * Current state of this exact token position.
   * Quantity is always non-negative.
   * side describes the current net inventory direction for this token ledger.
   */
  currentQuantity: number;
  currentSide: VenueSide | null;
  averageEntryPrice: number | null;

  /**
   * Fill being applied to this token ledger.
   * venueSide is exchange-facing only.
   * intent/inventoryEffect describe portfolio meaning.
   */
  fillSize: number;
  fillPrice: number;
  venueSide: VenueSide;
  intent: TradeIntent;
  inventoryEffect: InventoryEffect;
}

export interface PositionManagerResult {
  marketId: string;
  tokenId: string;
  outcome: Outcome;

  /**
   * Resulting token ledger quantity.
   */
  nextQuantity: number;

  /**
   * Resulting average entry price for remaining inventory.
   */
  nextAverageEntryPrice: number;

  /**
   * Net side of the remaining token inventory.
   * Null when fully flat.
   */
  nextSide: VenueSide | null;

  /**
   * Realized PnL generated by this fill against this token ledger.
   */
  realizedPnlDelta: number;

  /**
   * Whether the fill increased or decreased inventory.
   */
  inventoryEffect: InventoryEffect;

  /**
   * Whether this fill opened a new position, increased one, reduced one,
   * closed one, or flipped it.
   */
  transition:
    | 'opened'
    | 'increased'
    | 'reduced'
    | 'closed'
    | 'flipped'
    | 'unchanged';

  updatedAt: string;
}

export class PositionManager {
  applyFill(input: PositionManagerInput): PositionManagerResult {
    this.validate(input);

    const signedCurrentQuantity = this.toSignedQuantity(
      input.currentQuantity,
      input.currentSide,
    );
    const signedFillQuantity = this.toSignedQuantity(
      input.fillSize,
      input.venueSide,
    );

    const nextSignedQuantity = signedCurrentQuantity + signedFillQuantity;
    const nextQuantity = Math.abs(nextSignedQuantity);
    const nextSide = this.sideFromSignedQuantity(nextSignedQuantity);

    let nextAverageEntryPrice = input.averageEntryPrice ?? 0;
    let realizedPnlDelta = 0;

    const currentAbs = Math.abs(signedCurrentQuantity);
    const fillAbs = Math.abs(signedFillQuantity);

    if (currentAbs <= 1e-12) {
      nextAverageEntryPrice = fillAbs > 0 ? input.fillPrice : 0;
    } else if (Math.sign(signedCurrentQuantity) === Math.sign(signedFillQuantity)) {
      const weightedNotional =
        currentAbs * (input.averageEntryPrice ?? 0) + fillAbs * input.fillPrice;
      const weightedQty = currentAbs + fillAbs;
      nextAverageEntryPrice = weightedQty > 0 ? weightedNotional / weightedQty : 0;
    } else {
      const closingQty = Math.min(currentAbs, fillAbs);

      realizedPnlDelta =
        (input.fillPrice - (input.averageEntryPrice ?? 0)) *
        closingQty *
        Math.sign(signedCurrentQuantity);

      if (Math.abs(nextSignedQuantity) <= 1e-12) {
        nextAverageEntryPrice = 0;
      } else if (Math.sign(nextSignedQuantity) !== Math.sign(signedCurrentQuantity)) {
        nextAverageEntryPrice = input.fillPrice;
      } else {
        nextAverageEntryPrice = input.averageEntryPrice ?? 0;
      }
    }

    return {
      marketId: input.marketId,
      tokenId: input.tokenId,
      outcome: input.outcome,
      nextQuantity,
      nextAverageEntryPrice,
      nextSide,
      realizedPnlDelta,
      inventoryEffect: input.inventoryEffect,
      transition: this.resolveTransition({
        signedCurrentQuantity,
        signedFillQuantity,
        nextSignedQuantity,
      }),
      updatedAt: new Date().toISOString(),
    };
  }

  private validate(input: PositionManagerInput): void {
    if (!input.marketId || input.marketId.trim().length === 0) {
      throw new Error('PositionManager requires marketId.');
    }

    if (!input.tokenId || input.tokenId.trim().length === 0) {
      throw new Error('PositionManager requires tokenId.');
    }

    if (!Number.isFinite(input.currentQuantity) || input.currentQuantity < 0) {
      throw new Error('PositionManager requires non-negative currentQuantity.');
    }

    if (!Number.isFinite(input.fillSize) || input.fillSize <= 0) {
      throw new Error('PositionManager requires positive fillSize.');
    }

    if (!Number.isFinite(input.fillPrice) || input.fillPrice <= 0) {
      throw new Error('PositionManager requires positive fillPrice.');
    }

    if (input.currentQuantity > 0 && !input.currentSide) {
      throw new Error(
        'PositionManager requires currentSide when currentQuantity is greater than zero.',
      );
    }

    const expectedSide = this.resolveVenueSideFromIntent(input.intent);
    if (expectedSide && expectedSide !== input.venueSide) {
      throw new Error(
        `Intent and venueSide mismatch: intent=${input.intent} implies ${expectedSide}, received ${input.venueSide}.`,
      );
    }

    const expectedInventoryEffect = this.resolveInventoryEffectFromIntent(input.intent);
    if (
      expectedInventoryEffect &&
      input.inventoryEffect !== 'NEUTRAL' &&
      expectedInventoryEffect !== input.inventoryEffect
    ) {
      throw new Error(
        `Intent and inventoryEffect mismatch: intent=${input.intent} implies ${expectedInventoryEffect}, received ${input.inventoryEffect}.`,
      );
    }

    if (
      (input.intent === 'REDUCE' || input.intent === 'EXIT') &&
      input.currentQuantity <= 1e-12
    ) {
      throw new Error(
        `Cannot ${input.intent.toLowerCase()} token inventory when no current position exists for tokenId=${input.tokenId}.`,
      );
    }
  }

  private toSignedQuantity(
    quantity: number,
    side: VenueSide | null,
  ): number {
    if (!side || Math.abs(quantity) <= 1e-12) {
      return 0;
    }
    return side === 'BUY' ? quantity : -quantity;
  }

  private sideFromSignedQuantity(value: number): VenueSide | null {
    if (Math.abs(value) <= 1e-12) {
      return null;
    }
    return value > 0 ? 'BUY' : 'SELL';
  }

  private resolveTransition(input: {
    signedCurrentQuantity: number;
    signedFillQuantity: number;
    nextSignedQuantity: number;
  }): PositionManagerResult['transition'] {
    const currentAbs = Math.abs(input.signedCurrentQuantity);
    const fillAbs = Math.abs(input.signedFillQuantity);
    const nextAbs = Math.abs(input.nextSignedQuantity);

    if (fillAbs <= 1e-12) {
      return 'unchanged';
    }

    if (currentAbs <= 1e-12 && nextAbs > 0) {
      return 'opened';
    }

    if (Math.sign(input.signedCurrentQuantity) === Math.sign(input.signedFillQuantity)) {
      return 'increased';
    }

    if (nextAbs <= 1e-12) {
      return 'closed';
    }

    if (Math.sign(input.nextSignedQuantity) !== Math.sign(input.signedCurrentQuantity)) {
      return 'flipped';
    }

    if (nextAbs < currentAbs) {
      return 'reduced';
    }

    return 'unchanged';
  }

  private resolveVenueSideFromIntent(intent: TradeIntent): VenueSide | null {
    if (intent === 'ENTER') {
      return 'BUY';
    }
    if (intent === 'REDUCE' || intent === 'EXIT') {
      return 'SELL';
    }
    return null;
  }

  private resolveInventoryEffectFromIntent(
    intent: TradeIntent,
  ): InventoryEffect | null {
    if (intent === 'ENTER') {
      return 'INCREASE';
    }
    if (intent === 'REDUCE' || intent === 'EXIT') {
      return 'DECREASE';
    }
    if (intent === 'FLIP') {
      return 'NEUTRAL';
    }
    return null;
  }
}